USE [master]
GO

/****** Object:  Database [SignUp Asessment]    Script Date: 1/8/2023 10:08:21 AM ******/
CREATE DATABASE [SignUp Asessment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SignUp Asessment', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SignUp Asessment.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SignUp Asessment_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SignUp Asessment_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SignUp Asessment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SignUp Asessment] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SignUp Asessment] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SignUp Asessment] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SignUp Asessment] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SignUp Asessment] SET ARITHABORT OFF 
GO

ALTER DATABASE [SignUp Asessment] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SignUp Asessment] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SignUp Asessment] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SignUp Asessment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SignUp Asessment] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SignUp Asessment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SignUp Asessment] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SignUp Asessment] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SignUp Asessment] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SignUp Asessment] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SignUp Asessment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SignUp Asessment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SignUp Asessment] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SignUp Asessment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SignUp Asessment] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SignUp Asessment] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SignUp Asessment] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SignUp Asessment] SET RECOVERY FULL 
GO

ALTER DATABASE [SignUp Asessment] SET  MULTI_USER 
GO

ALTER DATABASE [SignUp Asessment] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SignUp Asessment] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SignUp Asessment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SignUp Asessment] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SignUp Asessment] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SignUp Asessment] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SignUp Asessment] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SignUp Asessment] SET  READ_WRITE 
GO

